server:
  port: ${PORT:0}

spring:
  application:
    name: pm-project-ws

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://afrozeprojectmanagement.us.auth0.com/.well-known/jwks.json
          issuer-uri: https://afrozeprojectmanagement.us.auth0.com/

  datasource:
    url: jdbc:postgresql://localhost:5432/project_management_project
    username: developer
    password: dev123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 10

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans,health,httptrace,info,metrics,circuitbreakers,circuitbreakerevents
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework: WARN
      apache: WARN
      hibernate: WARN

    com:
      netflix: WARN
      zaxxer: WARN
      afroze:
        projectmanagement:
          company:
            api: INFO
  file:
    name: logs\project-api.log
info:
  application:
    name: ${spring.application.name}
